---
- name: Config option "user"
  when:
    - ansible_os_family == 'Suse'
    - ansible_pkg_mgr == 'zypper'
  become: yes
  ini_file:
    path: '{{ tftpd_path_to_config_fact }}'
    section: null
    option: TFTP_USER
    value: '"{{ tftpd_user }}"'
    no_extra_spaces: yes
    state: present
    backup: yes
  notify: restart-tftpd

- name: Config option "directory"
  when:
    - ansible_os_family == 'Suse'
    - ansible_pkg_mgr == 'zypper'
  become: yes
  ini_file:
    path: '{{ tftpd_path_to_config_fact }}'
    section: null
    option: TFTP_DIRECTORY
    value: '"{{ tftpd_directory }}"'
    no_extra_spaces: yes
    state: present
    backup: yes
  notify: restart-tftpd

- name: Config option "options"
  when:
    - ansible_os_family == 'Suse'
    - ansible_pkg_mgr == 'zypper'
  become: yes
  ini_file:
    path: '{{ tftpd_path_to_config_fact }}'
    section: null
    option: TFTP_OPTIONS
    value: '"{{ tftpd_options }}"'
    no_extra_spaces: yes
    state: present
    backup: yes
  notify: restart-tftpd
