---
# https://askubuntu.com/a/659268
# https://valynkin.ru/shpargalka-po-systemd-systemctl.html
- name: Create dir 4 systemd service custom setting
  when:
    - ansible_os_family == 'RedHat'
    - ansible_pkg_mgr == 'dnf'
  become: yes
  file:
    path: "{{ tftpd_path_to_config_fact | dirname }}"
    state: directory

- name: Override default systemd unit
  when:
    - ansible_os_family == 'RedHat'
    - ansible_pkg_mgr == 'dnf'
  become: yes
  copy:
    dest: '{{ tftpd_path_to_config_fact }}'
    content: |
      [Unit]
      Description=Tftp Server
      Requires=tftp.socket
      Documentation=man:in.tftpd

      [Service]
      # https://unix.stackexchange.com/a/500267
      ExecStart=
      ExecStart=/usr/sbin/in.tftpd --address {{ tftpd_address }}:{{ tftpd_port }} {{ tftpd_options }} {{ tftpd_directory }} --user {{ tftpd_user }}
      StandardInput=socket

      [Install]
      Also=tftp.socket
  register: tftp_config_full_override

# Не notify, потому что handler выполняется последним и смена конфига приводит к запрету запуска при загрузке.
- name: Reload systemd when unit file was changed
  when:
    - ansible_system == 'Linux'
    # - tftp_config_full_override.changed == true
    - tftp_config_full_override.changed
  become: yes
  systemd:
    name: "{{ tftpd_service_name_fact }}"
    daemon_reload: yes
