---
- name: Create tftpd group
  when: ansible_system == 'Linux'
  become: true
  group:
    name: '{{ tftpd_group }}'
    system: true
    state: present

- name: Create tftpd user
  when: ansible_system == 'Linux'
  become: true
  user:
    name: '{{ tftpd_user }}'
    group: '{{ tftpd_group }}'
    home: '{{ tftpd_directory }}'
    create_home: false
    shell: /usr/sbin/nologin
    state: present
    system: true
