---
- include_tasks: update-cache.yml
  when: ansible_virtualization_type == 'docker'

- include_tasks: create-user-and-group.yml

- include_tasks: install-tftd.yml

- include_tasks: config-tftpd.yml
